logging:
  config: classpath:log4j2.xml

spring:
  application:
    name: rabbitmqconsumer

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:rabbitmq}
    password: ${RABBITMQ_PASSWORD:rabbitmq}
    listener:
      simple:
        prefetch: 10
        concurrency: 1
        max-concurrency: 3
        default-requeue-rejected: false
        retry:
          enabled: true
          max-retries: 3
          initial-interval: 1s
          multiplier: 2

rabbitmq:
  pedidos:
    fila: pedidos.criados
    fila-dlq: pedidos.criados.dlq
    exchange: pedidos.exchange
    routing-key: pedido.criado
    exchange-dlq: pedidos.dlx

---

spring:
  config:
    activate:
      on-profile: test

rabbitmq:
  pedidos:
    fila: pedidos.criados.test
    fila-dlq: pedidos.criados.test.dlq
    exchange: pedidos.exchange.test
    routing-key: pedido.criado.test
    exchange-dlq: pedidos.dlx.test